title: Texture Theme
author: GitHub User
email: your-email@domain.com
description:  # this means to ignore newlines until "show_exerpts:"
  Investigating the FAO Dataset
show_excerpts: false # set to true to show excerpts on the homepage
baseurl: /ada/
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: :title
texture:
  title: "Environmental Impact of Agricultural Practices in the World"
  tagline: "CS401 - 2019/2020"
  authorline: "T. Bian, E. Holzl, R. Laporte"
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    github:  OnlineGardenGnome/ADA_Project
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed